server:
  port: 8080

spring:
  application:
    name: stock-service

  data:
    mongodb:
      uri: mongodb://stock-app:stock%40123@mongodb-local:27017/stock

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  kafka:
    consumer:
      group-id: stock-service
      auto-offset-reset: earliest
    bootstrap-servers: kafka-local:9092

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
