server:
  port: 8082

spring:
  application:
    name: payment-service

  data:
    mongodb:
      uri: mongodb://payment-app:payment%40123@mongodb-local:27017/payment

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  kafka:
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
    bootstrap-servers: kafka-local:9092

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
