version: '3.7'

services:
  mongodb:
    container_name: mongodb
    image: docker.io/bitnami/mongodb:latest
    ports: 
      - "27017:27017"
    environment: 
      - MONGODB_ROOT_PASSWORD=123456
    networks:
      - mongodb
    volumes: 
      - 'mongodb_data:/bitnami/mongodb'

volumes: 
  mongodb_data:
    driver: local

networks: 
  mongodb: