server:
  port: 8081

spring:
  application:
    name: order-service

  data:
    mongodb:
      uri: mongodb://order-app:order%40123@mongodb-local:27017/order

  kafka:
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
    bootstrap-servers: kafka-local:9092

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  topics:
    orders-log: orders-log