server:
  port: 8081

spring:
  application:
    name: order-service

  data:
    mongodb:
      uri: mongodb://order-app:order%40123@localhost:27017/order

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

  kafka:
    consumer:
      group-id: order-service
      auto-offset-reset: earliest

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
